on:
  push:
  pull_request:

name: check_r_style

jobs:
  check_r_style:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install libcurl4-openssl-dev
        run: sudo apt install libcurl4-openssl-dev

      - name: Install dependencies
        run: Rscript -e 'install.packages("lintr")'

      - name: Check for style
        run: Rscript -e 'lintr::lint_dir(".")'

